name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        script_name:
        - main
        - antiafk

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: ${{ matrix.script_name }}.spec

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.script_name }}
        path: dist/windows/${{ matrix.script_name }}.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/windows/${{ matrix.script_name }}.exe